test(print): prevent environment leakage in prompt tests
The `prompt_with_all` and `rprompt_with_all` tests were failing here
because they accessed real environment data instead of using isolated
test environments. This was observed with `gcloud` and caused tests to
fail with output like:

```
thread 'print::test::prompt_with_all' panicked at src/print.rs:576:9:
assertion `left == right` failed
  left: ">"
 right: "on \u{1b}[1;34m☁\u{fe0f}  user@example.com\u{1b}[0m >"
```

Fix by setting HOME="/dev/null" (or "nul" on Windows) in these tests to
prevent modules from accessing real configuration files.